PGDMP         3            	    {         
   EducationalDB    15.4    15.4     №
           0    0    ENCODING    ENCODING        SET client_encoding = 'UTF8';
                      false            є
           0    0 
   STDSTRINGS 
   STDSTRINGS     (   SET standard_conforming_strings = 'on';
                      false            »
           0    0 
   SEARCHPATH 
   SEARCHPATH     8   SELECT pg_catalog.set_config('search_path', '', false);
                      false            ј
           1262    33748 
   EducationalDB    DATABASE     ѓ   CREATE DATABASE "EducationalDB" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Russian_Russia.1251';
    DROP DATABASE "EducationalDB";
                postgres    false                        2615    40910 
   production    SCHEMA        CREATE SCHEMA production;
    DROP SCHEMA production;
                postgres    false            п            1259    40928    knot    TABLE     В   CREATE TABLE production.knot (
    id integer NOT NULL,
    title text NOT NULL,
    cost integer NOT NULL,
    region_id integer NOT NULL,
    CONSTRAINT knot_cost_check CHECK ((cost >= 0))
);
    DROP TABLE production.knot;
    
   production         heap    postgres    false    6            о            1259    40927    knot_id_seq    SEQUENCE     П   ALTER TABLE production.knot ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME production.knot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
         
   production          postgres    false    6    239            н            1259    40920    product    TABLE     ­   CREATE TABLE production.product (
    id integer NOT NULL,
    title text NOT NULL,
    complexity integer NOT NULL,
    datecreated timestamp(6) with time zone NOT NULL
);
    DROP TABLE production.product;
    
   production         heap    postgres    false    6            м            1259    40919    product_id_seq    SEQUENCE     Х   ALTER TABLE production.product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME production.product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
         
   production          postgres    false    6    237            ц            1259    40993    product_knot    TABLE     h   CREATE TABLE production.product_knot (
    product_id integer NOT NULL,
    knot_id integer NOT NULL
);
 $   DROP TABLE production.product_knot;
    
   production         heap    postgres    false    6            х            1259    40966 
   production    TABLE     =  CREATE TABLE production.production (
    id integer NOT NULL,
    title text NOT NULL,
    datecreated timestamp(6) with time zone NOT NULL,
    datedelete timestamp(6) with time zone,
    product_id integer NOT NULL,
    workshop_id integer NOT NULL,
    region_id integer NOT NULL,
    staff_id integer NOT NULL
);
 "   DROP TABLE production.production;
    
   production         heap    postgres    false    6            ф            1259    40965    production_id_seq    SEQUENCE     Ы   ALTER TABLE production.production ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME production.production_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
         
   production          postgres    false    6    245            л            1259    40912    region    TABLE     U   CREATE TABLE production.region (
    id integer NOT NULL,
    title text NOT NULL
);
    DROP TABLE production.region;
    
   production         heap    postgres    false    6            к            1259    40911 
   region_id_seq    SEQUENCE     У   ALTER TABLE production.region ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME production.region_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
         
   production          postgres    false    235    6            у            1259    40950    staff    TABLE        CREATE TABLE production.staff (
    id integer NOT NULL,
    title text NOT NULL,
    first_name text NOT NULL,
    second_name text NOT NULL,
    last_name text NOT NULL,
    phone_number text NOT NULL,
    address text NOT NULL,
    post text NOT NULL,
    full_name text GENERATED ALWAYS AS ((((((first_name || ' '::text) || "left"(second_name, 1)) || '.'::text) || "left"(last_name, 1)) || '.'::text)) STORED
);
    DROP TABLE production.staff;
    
   production         heap    postgres    false    6            т            1259    40949    staff_id_seq    SEQUENCE     €   CREATE SEQUENCE production.staff_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
 '   DROP SEQUENCE production.staff_id_seq;
    
   production          postgres    false    243    6            Ѕ
           0    0    staff_id_seq    SEQUENCE OWNED BY     E   ALTER SEQUENCE production.staff_id_seq OWNED BY production.staff.id;
       
   production          postgres    false    242            ъ            1259    41032    staff_region    TABLE     h   CREATE TABLE production.staff_region (
    staff_id integer NOT NULL,
    region_id integer NOT NULL
);
 $   DROP TABLE production.staff_region;
    
   production         heap    postgres    false    6            ы            1259    41045    staff_workshop    TABLE     l   CREATE TABLE production.staff_workshop (
    staff_id integer NOT NULL,
    workshop_id integer NOT NULL
);
 &   DROP TABLE production.staff_workshop;
    
   production         heap    postgres    false    6            щ            1259    41020 
   working_shift    TABLE     п   CREATE TABLE production.working_shift (
    id integer NOT NULL,
    title text NOT NULL,
    shift_start_date timestamp(6) with time zone NOT NULL,
    shift_end_date timestamp(6) with time zone NOT NULL,
    staff_id integer NOT NULL
);
 %   DROP TABLE production.working_shift;
    
   production         heap    postgres    false    6            ш            1259    41019    working_shift_id_seq    SEQUENCE     б   ALTER TABLE production.working_shift ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME production.working_shift_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
         
   production          postgres    false    249    6            с            1259    40942    workshop    TABLE     t   CREATE TABLE production.workshop (
    id integer NOT NULL,
    title text NOT NULL,
    chef_name text NOT NULL
);
     DROP TABLE production.workshop;
    
   production         heap    postgres    false    6            р            1259    40941    workshop_id_seq    SEQUENCE     Ч   ALTER TABLE production.workshop ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME production.workshop_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
         
   production          postgres    false    241    6            ч            1259    41006    workshop_region    TABLE     n   CREATE TABLE production.workshop_region (
    workshop_id integer NOT NULL,
    region_id integer NOT NULL
);
 '   DROP TABLE production.workshop_region;
    
   production         heap    postgres    false    6            й            1259    35319    cars    TABLE     Џ   CREATE TABLE public.cars (
    id integer NOT NULL,
    title text NOT NULL,
    mark text NOT NULL,
    typesofmachine_id integer NOT NULL
);
    DROP TABLE public.cars;
       public         heap    postgres    false            и            1259    35318    cars_id_seq    SEQUENCE     З   ALTER TABLE public.cars ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cars_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
            public          postgres    false    233            Ю            1259    35238    machines    TABLE     ћ   CREATE TABLE public.machines (
    id integer NOT NULL,
    title text NOT NULL,
    workshop_id integer NOT NULL,
    machines_status_id integer NOT NULL
);
    DROP TABLE public.machines;
       public         heap    postgres    false            Э            1259    35237    machines_id_seq    SEQUENCE     П   ALTER TABLE public.machines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.machines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
            public          postgres    false    222            Ъ            1259    35222    machines_status    TABLE     Z   CREATE TABLE public.machines_status (
    id integer NOT NULL,
    title text NOT NULL
);
 #   DROP TABLE public.machines_status;
       public         heap    postgres    false            Щ            1259    35221    machines_status_id_seq    SEQUENCE     Э   ALTER TABLE public.machines_status ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.machines_status_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
            public          postgres    false    218            д            1259    35290    material_workshop    TABLE     \   CREATE TABLE public.material_workshop (
    material_id integer,
    workshop_id integer
);
 %   DROP TABLE public.material_workshop;
       public         heap    postgres    false            г            1259    35282 	   materials    TABLE     Ћ   CREATE TABLE public.materials (
    id integer NOT NULL,
    title text NOT NULL,
    price integer NOT NULL,
    is_used boolean NOT NULL
);
    DROP TABLE public.materials;
       public         heap    postgres    false            б            1259    35280    materials_id_seq    SEQUENCE     С   ALTER TABLE public.materials ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.materials_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
            public          postgres    false    227            в            1259    35281    materials_price_seq    SEQUENCE     ‹   CREATE SEQUENCE public.materials_price_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
 *   DROP SEQUENCE public.materials_price_seq;
       public          postgres    false    227            ѕ
           0    0    materials_price_seq    SEQUENCE OWNED BY     K   ALTER SEQUENCE public.materials_price_seq OWNED BY public.materials.price;
          public          postgres    false    226            Ш            1259    35214    shift    TABLE     P   CREATE TABLE public.shift (
    id integer NOT NULL,
    title text NOT NULL
);
    DROP TABLE public.shift;
       public         heap    postgres    false            Ч            1259    35213    shift_id_seq    SEQUENCE     Й   ALTER TABLE public.shift ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shift_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
            public          postgres    false    216            а            1259    35256    staff    TABLE     ¬  CREATE TABLE public.staff (
    id integer NOT NULL,
    firstname text NOT NULL,
    secondname text NOT NULL,
    lastname text NOT NULL,
    phonenumber text NOT NULL,
    address text NOT NULL,
    is_active boolean NOT NULL,
    datecreated timestamp(6) with time zone NOT NULL,
    datedelete timestamp(6) with time zone,
    shift_id integer NOT NULL,
    machine_id integer NOT NULL,
    workshop_id integer NOT NULL
);
    DROP TABLE public.staff;
       public         heap    postgres    false            Я            1259    35255    staff_id_seq    SEQUENCE     Й   ALTER TABLE public.staff ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.staff_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
            public          postgres    false    224            з            1259    35305    types_of_machines    TABLE     І   CREATE TABLE public.types_of_machines (
    id integer NOT NULL,
    title text NOT NULL,
    price integer NOT NULL,
    body text NOT NULL,
    workshop_id integer NOT NULL
);
 %   DROP TABLE public.types_of_machines;
       public         heap    postgres    false            е            1259    35303    types_of_machines_id_seq    SEQUENCE     б   ALTER TABLE public.types_of_machines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.types_of_machines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
            public          postgres    false    231            ж            1259    35304    types_of_machines_price_seq    SEQUENCE     “   CREATE SEQUENCE public.types_of_machines_price_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
 2   DROP SEQUENCE public.types_of_machines_price_seq;
       public          postgres    false    231            ї
           0    0    types_of_machines_price_seq    SEQUENCE OWNED BY     [   ALTER SEQUENCE public.types_of_machines_price_seq OWNED BY public.types_of_machines.price;
          public          postgres    false    230            Ь            1259    35230 	   workshops    TABLE     T   CREATE TABLE public.workshops (
    id integer NOT NULL,
    title text NOT NULL
);
    DROP TABLE public.workshops;
       public         heap    postgres    false            Ы            1259    35229    workshops_id_seq    SEQUENCE     С   ALTER TABLE public.workshops ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workshops_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
            public          postgres    false    220            Д           2604    40953    staff id    DEFAULT     l   ALTER TABLE ONLY production.staff ALTER COLUMN id SET DEFAULT nextval('production.staff_id_seq'::regclass);
 ;   ALTER TABLE production.staff ALTER COLUMN id DROP DEFAULT;
    
   production          postgres    false    242    243    243            В           2604    35285    materials price    DEFAULT     r   ALTER TABLE ONLY public.materials ALTER COLUMN price SET DEFAULT nextval('public.materials_price_seq'::regclass);
 >   ALTER TABLE public.materials ALTER COLUMN price DROP DEFAULT;
       public          postgres    false    227    226    227            Г           2604    35308    types_of_machines price    DEFAULT     ‚   ALTER TABLE ONLY public.types_of_machines ALTER COLUMN price SET DEFAULT nextval('public.types_of_machines_price_seq'::regclass);
 F   ALTER TABLE public.types_of_machines ALTER COLUMN price DROP DEFAULT;
       public          postgres    false    230    231    231            Є
          0    40928    knot 
   TABLE DATA           >   COPY production.knot (id, title, cost, region_id) FROM stdin;
 
   production          postgres    false    239    ›       Ё
          0    40920    product 
   TABLE DATA           I   COPY production.product (id, title, complexity, datecreated) FROM stdin;
 
   production          postgres    false    237   Йњ       ±
          0    40993    product_knot 
   TABLE DATA           ?   COPY production.product_knot (product_id, knot_id) FROM stdin;
 
   production          postgres    false    246   5ќ       °
          0    40966 
   production 
   TABLE DATA           z   COPY production.production (id, title, datecreated, datedelete, product_id, workshop_id, region_id, staff_id) FROM stdin;
 
   production          postgres    false    245   yќ       ¦
          0    40912    region 
   TABLE DATA           /   COPY production.region (id, title) FROM stdin;
 
   production          postgres    false    235   ыќ       ®
          0    40950    staff 
   TABLE DATA           o   COPY production.staff (id, title, first_name, second_name, last_name, phone_number, address, post) FROM stdin;
 
   production          postgres    false    243   kћ       µ
          0    41032    staff_region 
   TABLE DATA           ?   COPY production.staff_region (staff_id, region_id) FROM stdin;
 
   production          postgres    false    250   oџ       ¶
          0    41045    staff_workshop 
   TABLE DATA           C   COPY production.staff_workshop (staff_id, workshop_id) FROM stdin;
 
   production          postgres    false    251   џџ       ґ
          0    41020 
   working_shift 
   TABLE DATA           b   COPY production.working_shift (id, title, shift_start_date, shift_end_date, staff_id) FROM stdin;
 
   production          postgres    false    249   Еџ       ¬
          0    40942    workshop 
   TABLE DATA           <   COPY production.workshop (id, title, chef_name) FROM stdin;
 
   production          postgres    false    241           І
          0    41006    workshop_region 
   TABLE DATA           E   COPY production.workshop_region (workshop_id, region_id) FROM stdin;
 
   production          postgres    false    247   i        ¤
          0    35319    cars 
   TABLE DATA           B   COPY public.cars (id, title, mark, typesofmachine_id) FROM stdin;
    public          postgres    false    233   •        ™
          0    35238    machines 
   TABLE DATA           N   COPY public.machines (id, title, workshop_id, machines_status_id) FROM stdin;
    public          postgres    false    222   І        •
          0    35222    machines_status 
   TABLE DATA           4   COPY public.machines_status (id, title) FROM stdin;
    public          postgres    false    218   П        џ
          0    35290    material_workshop 
   TABLE DATA           E   COPY public.material_workshop (material_id, workshop_id) FROM stdin;
    public          postgres    false    228   м        ћ
          0    35282 	   materials 
   TABLE DATA           >   COPY public.materials (id, title, price, is_used) FROM stdin;
    public          postgres    false    227   	Ў       “
          0    35214    shift 
   TABLE DATA           *   COPY public.shift (id, title) FROM stdin;
    public          postgres    false    216   &Ў       ›
          0    35256    staff 
   TABLE DATA           Ў   COPY public.staff (id, firstname, secondname, lastname, phonenumber, address, is_active, datecreated, datedelete, shift_id, machine_id, workshop_id) FROM stdin;
    public          postgres    false    224   CЎ       ў
          0    35305    types_of_machines 
   TABLE DATA           P   COPY public.types_of_machines (id, title, price, body, workshop_id) FROM stdin;
    public          postgres    false    231   `Ў       —
          0    35230 	   workshops 
   TABLE DATA           .   COPY public.workshops (id, title) FROM stdin;
    public          postgres    false    220   }Ў       А
           0    0    knot_id_seq    SEQUENCE SET     >   SELECT pg_catalog.setval('production.knot_id_seq', 18, true);
       
   production          postgres    false    238            Б
           0    0    product_id_seq    SEQUENCE SET     @   SELECT pg_catalog.setval('production.product_id_seq', 3, true);
       
   production          postgres    false    236            В
           0    0    production_id_seq    SEQUENCE SET     C   SELECT pg_catalog.setval('production.production_id_seq', 3, true);
       
   production          postgres    false    244            Г
           0    0 
   region_id_seq    SEQUENCE SET     ?   SELECT pg_catalog.setval('production.region_id_seq', 5, true);
       
   production          postgres    false    234            Д
           0    0    staff_id_seq    SEQUENCE SET     >   SELECT pg_catalog.setval('production.staff_id_seq', 3, true);
       
   production          postgres    false    242            Е
           0    0    working_shift_id_seq    SEQUENCE SET     F   SELECT pg_catalog.setval('production.working_shift_id_seq', 3, true);
       
   production          postgres    false    248            Ж
           0    0    workshop_id_seq    SEQUENCE SET     A   SELECT pg_catalog.setval('production.workshop_id_seq', 1, true);
       
   production          postgres    false    240            З
           0    0    cars_id_seq    SEQUENCE SET     :   SELECT pg_catalog.setval('public.cars_id_seq', 1, false);
          public          postgres    false    232            И
           0    0    machines_id_seq    SEQUENCE SET     >   SELECT pg_catalog.setval('public.machines_id_seq', 1, false);
          public          postgres    false    221            Й
           0    0    machines_status_id_seq    SEQUENCE SET     E   SELECT pg_catalog.setval('public.machines_status_id_seq', 1, false);
          public          postgres    false    217            К
           0    0    materials_id_seq    SEQUENCE SET     ?   SELECT pg_catalog.setval('public.materials_id_seq', 1, false);
          public          postgres    false    225            Л
           0    0    materials_price_seq    SEQUENCE SET     B   SELECT pg_catalog.setval('public.materials_price_seq', 1, false);
          public          postgres    false    226            М
           0    0    shift_id_seq    SEQUENCE SET     ;   SELECT pg_catalog.setval('public.shift_id_seq', 1, false);
          public          postgres    false    215            Н
           0    0    staff_id_seq    SEQUENCE SET     ;   SELECT pg_catalog.setval('public.staff_id_seq', 1, false);
          public          postgres    false    223            О
           0    0    types_of_machines_id_seq    SEQUENCE SET     G   SELECT pg_catalog.setval('public.types_of_machines_id_seq', 1, false);
          public          postgres    false    229            П
           0    0    types_of_machines_price_seq    SEQUENCE SET     J   SELECT pg_catalog.setval('public.types_of_machines_price_seq', 1, false);
          public          postgres    false    230            Р
           0    0    workshops_id_seq    SEQUENCE SET     ?   SELECT pg_catalog.setval('public.workshops_id_seq', 1, false);
          public          postgres    false    219            Ю           2606    40935    knot knot_pkey 
   CONSTRAINT     P   ALTER TABLE ONLY production.knot
    ADD CONSTRAINT knot_pkey PRIMARY KEY (id);
 <   ALTER TABLE ONLY production.knot DROP CONSTRAINT knot_pkey;
    
   production            postgres    false    239            Ь           2606    40926    product product_pkey 
   CONSTRAINT     V   ALTER TABLE ONLY production.product
    ADD CONSTRAINT product_pkey PRIMARY KEY (id);
 B   ALTER TABLE ONLY production.product DROP CONSTRAINT product_pkey;
    
   production            postgres    false    237            к           2606    40972    production production_pkey 
   CONSTRAINT     \   ALTER TABLE ONLY production.production
    ADD CONSTRAINT production_pkey PRIMARY KEY (id);
 H   ALTER TABLE ONLY production.production DROP CONSTRAINT production_pkey;
    
   production            postgres    false    245            Ъ           2606    40918    region region_pkey 
   CONSTRAINT     T   ALTER TABLE ONLY production.region
    ADD CONSTRAINT region_pkey PRIMARY KEY (id);
 @   ALTER TABLE ONLY production.region DROP CONSTRAINT region_pkey;
    
   production            postgres    false    235            в           2606    40962    staff staff_address_key 
   CONSTRAINT     Y   ALTER TABLE ONLY production.staff
    ADD CONSTRAINT staff_address_key UNIQUE (address);
 E   ALTER TABLE ONLY production.staff DROP CONSTRAINT staff_address_key;
    
   production            postgres    false    243            д           2606    40960    staff staff_phone_number_key 
   CONSTRAINT     c   ALTER TABLE ONLY production.staff
    ADD CONSTRAINT staff_phone_number_key UNIQUE (phone_number);
 J   ALTER TABLE ONLY production.staff DROP CONSTRAINT staff_phone_number_key;
    
   production            postgres    false    243            ж           2606    40958    staff staff_pkey 
   CONSTRAINT     R   ALTER TABLE ONLY production.staff
    ADD CONSTRAINT staff_pkey PRIMARY KEY (id);
 >   ALTER TABLE ONLY production.staff DROP CONSTRAINT staff_pkey;
    
   production            postgres    false    243            и           2606    40964    staff staff_post_key 
   CONSTRAINT     S   ALTER TABLE ONLY production.staff
    ADD CONSTRAINT staff_post_key UNIQUE (post);
 B   ALTER TABLE ONLY production.staff DROP CONSTRAINT staff_post_key;
    
   production            postgres    false    243            м           2606    41026     working_shift working_shift_pkey 
   CONSTRAINT     b   ALTER TABLE ONLY production.working_shift
    ADD CONSTRAINT working_shift_pkey PRIMARY KEY (id);
 N   ALTER TABLE ONLY production.working_shift DROP CONSTRAINT working_shift_pkey;
    
   production            postgres    false    249            а           2606    40948    workshop workshop_pkey 
   CONSTRAINT     X   ALTER TABLE ONLY production.workshop
    ADD CONSTRAINT workshop_pkey PRIMARY KEY (id);
 D   ALTER TABLE ONLY production.workshop DROP CONSTRAINT workshop_pkey;
    
   production            postgres    false    241            Ш           2606    35325    cars cars_pkey 
   CONSTRAINT     L   ALTER TABLE ONLY public.cars
    ADD CONSTRAINT cars_pkey PRIMARY KEY (id);
 8   ALTER TABLE ONLY public.cars DROP CONSTRAINT cars_pkey;
       public            postgres    false    233            О           2606    35244    machines machines_pkey 
   CONSTRAINT     T   ALTER TABLE ONLY public.machines
    ADD CONSTRAINT machines_pkey PRIMARY KEY (id);
 @   ALTER TABLE ONLY public.machines DROP CONSTRAINT machines_pkey;
       public            postgres    false    222            К           2606    35228 $   machines_status machines_status_pkey 
   CONSTRAINT     b   ALTER TABLE ONLY public.machines_status
    ADD CONSTRAINT machines_status_pkey PRIMARY KEY (id);
 N   ALTER TABLE ONLY public.machines_status DROP CONSTRAINT machines_status_pkey;
       public            postgres    false    218            Ф           2606    35289    materials materials_pkey 
   CONSTRAINT     V   ALTER TABLE ONLY public.materials
    ADD CONSTRAINT materials_pkey PRIMARY KEY (id);
 B   ALTER TABLE ONLY public.materials DROP CONSTRAINT materials_pkey;
       public            postgres    false    227            И           2606    35220    shift shift_pkey 
   CONSTRAINT     N   ALTER TABLE ONLY public.shift
    ADD CONSTRAINT shift_pkey PRIMARY KEY (id);
 :   ALTER TABLE ONLY public.shift DROP CONSTRAINT shift_pkey;
       public            postgres    false    216            Р           2606    35264    staff staff_address_key 
   CONSTRAINT     U   ALTER TABLE ONLY public.staff
    ADD CONSTRAINT staff_address_key UNIQUE (address);
 A   ALTER TABLE ONLY public.staff DROP CONSTRAINT staff_address_key;
       public            postgres    false    224            Т           2606    35262    staff staff_pkey 
   CONSTRAINT     N   ALTER TABLE ONLY public.staff
    ADD CONSTRAINT staff_pkey PRIMARY KEY (id);
 :   ALTER TABLE ONLY public.staff DROP CONSTRAINT staff_pkey;
       public            postgres    false    224            Ц           2606    35312 (   types_of_machines types_of_machines_pkey 
   CONSTRAINT     f   ALTER TABLE ONLY public.types_of_machines
    ADD CONSTRAINT types_of_machines_pkey PRIMARY KEY (id);
 R   ALTER TABLE ONLY public.types_of_machines DROP CONSTRAINT types_of_machines_pkey;
       public            postgres    false    231            М           2606    35236    workshops workshops_pkey 
   CONSTRAINT     V   ALTER TABLE ONLY public.workshops
    ADD CONSTRAINT workshops_pkey PRIMARY KEY (id);
 B   ALTER TABLE ONLY public.workshops DROP CONSTRAINT workshops_pkey;
       public            postgres    false    220            ц           2606    40936    knot knot_region_id_fkey 
   FK CONSTRAINT     ”   ALTER TABLE ONLY production.knot
    ADD CONSTRAINT knot_region_id_fkey FOREIGN KEY (region_id) REFERENCES production.region(id) ON DELETE CASCADE;
 F   ALTER TABLE ONLY production.knot DROP CONSTRAINT knot_region_id_fkey;
    
   production          postgres    false    3290    239    235            ы           2606    41001 &   product_knot product_knot_knot_id_fkey 
   FK CONSTRAINT     ћ   ALTER TABLE ONLY production.product_knot
    ADD CONSTRAINT product_knot_knot_id_fkey FOREIGN KEY (knot_id) REFERENCES production.knot(id) ON DELETE CASCADE;
 T   ALTER TABLE ONLY production.product_knot DROP CONSTRAINT product_knot_knot_id_fkey;
    
   production          postgres    false    246    239    3294            ь           2606    40996 )   product_knot product_knot_product_id_fkey 
   FK CONSTRAINT     §   ALTER TABLE ONLY production.product_knot
    ADD CONSTRAINT product_knot_product_id_fkey FOREIGN KEY (product_id) REFERENCES production.product(id) ON DELETE CASCADE;
 W   ALTER TABLE ONLY production.product_knot DROP CONSTRAINT product_knot_product_id_fkey;
    
   production          postgres    false    237    246    3292            ч           2606    40973 %   production production_product_id_fkey 
   FK CONSTRAINT     Ј   ALTER TABLE ONLY production.production
    ADD CONSTRAINT production_product_id_fkey FOREIGN KEY (product_id) REFERENCES production.product(id) ON DELETE CASCADE;
 S   ALTER TABLE ONLY production.production DROP CONSTRAINT production_product_id_fkey;
    
   production          postgres    false    3292    237    245            ш           2606    40983 $   production production_region_id_fkey 
   FK CONSTRAINT         ALTER TABLE ONLY production.production
    ADD CONSTRAINT production_region_id_fkey FOREIGN KEY (region_id) REFERENCES production.region(id) ON DELETE CASCADE;
 R   ALTER TABLE ONLY production.production DROP CONSTRAINT production_region_id_fkey;
    
   production          postgres    false    235    245    3290            щ           2606    40988 #   production production_staff_id_fkey 
   FK CONSTRAINT     ќ   ALTER TABLE ONLY production.production
    ADD CONSTRAINT production_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES production.staff(id) ON DELETE CASCADE;
 Q   ALTER TABLE ONLY production.production DROP CONSTRAINT production_staff_id_fkey;
    
   production          postgres    false    243    245    3302            ъ           2606    40978 &   production production_workshop_id_fkey 
   FK CONSTRAINT     ¦   ALTER TABLE ONLY production.production
    ADD CONSTRAINT production_workshop_id_fkey FOREIGN KEY (workshop_id) REFERENCES production.workshop(id) ON DELETE CASCADE;
 T   ALTER TABLE ONLY production.production DROP CONSTRAINT production_workshop_id_fkey;
    
   production          postgres    false    241    3296    245             
           2606    41040 (   staff_region staff_region_region_id_fkey 
   FK CONSTRAINT     ¤   ALTER TABLE ONLY production.staff_region
    ADD CONSTRAINT staff_region_region_id_fkey FOREIGN KEY (region_id) REFERENCES production.region(id) ON DELETE CASCADE;
 V   ALTER TABLE ONLY production.staff_region DROP CONSTRAINT staff_region_region_id_fkey;
    
   production          postgres    false    3290    235    250            
           2606    41035 '   staff_region staff_region_staff_id_fkey 
   FK CONSTRAINT     Ў   ALTER TABLE ONLY production.staff_region
    ADD CONSTRAINT staff_region_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES production.staff(id) ON DELETE CASCADE;
 U   ALTER TABLE ONLY production.staff_region DROP CONSTRAINT staff_region_staff_id_fkey;
    
   production          postgres    false    250    243    3302            
           2606    41048 +   staff_workshop staff_workshop_staff_id_fkey 
   FK CONSTRAINT     Ґ   ALTER TABLE ONLY production.staff_workshop
    ADD CONSTRAINT staff_workshop_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES production.staff(id) ON DELETE CASCADE;
 Y   ALTER TABLE ONLY production.staff_workshop DROP CONSTRAINT staff_workshop_staff_id_fkey;
    
   production          postgres    false    3302    243    251            
           2606    41053 .   staff_workshop staff_workshop_workshop_id_fkey 
   FK CONSTRAINT     ®   ALTER TABLE ONLY production.staff_workshop
    ADD CONSTRAINT staff_workshop_workshop_id_fkey FOREIGN KEY (workshop_id) REFERENCES production.workshop(id) ON DELETE CASCADE;
 \   ALTER TABLE ONLY production.staff_workshop DROP CONSTRAINT staff_workshop_workshop_id_fkey;
    
   production          postgres    false    251    3296    241            я           2606    41027 )   working_shift working_shift_staff_id_fkey 
   FK CONSTRAINT     Ј   ALTER TABLE ONLY production.working_shift
    ADD CONSTRAINT working_shift_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES production.staff(id) ON DELETE CASCADE;
 W   ALTER TABLE ONLY production.working_shift DROP CONSTRAINT working_shift_staff_id_fkey;
    
   production          postgres    false    243    249    3302            э           2606    41014 .   workshop_region workshop_region_region_id_fkey 
   FK CONSTRAINT     Є   ALTER TABLE ONLY production.workshop_region
    ADD CONSTRAINT workshop_region_region_id_fkey FOREIGN KEY (region_id) REFERENCES production.region(id) ON DELETE CASCADE;
 \   ALTER TABLE ONLY production.workshop_region DROP CONSTRAINT workshop_region_region_id_fkey;
    
   production          postgres    false    247    235    3290            ю           2606    41009 0   workshop_region workshop_region_workshop_id_fkey 
   FK CONSTRAINT     °   ALTER TABLE ONLY production.workshop_region
    ADD CONSTRAINT workshop_region_workshop_id_fkey FOREIGN KEY (workshop_id) REFERENCES production.workshop(id) ON DELETE CASCADE;
 ^   ALTER TABLE ONLY production.workshop_region DROP CONSTRAINT workshop_region_workshop_id_fkey;
    
   production          postgres    false    247    241    3296            х           2606    35326     cars cars_typesofmachine_id_fkey 
   FK CONSTRAINT     §   ALTER TABLE ONLY public.cars
    ADD CONSTRAINT cars_typesofmachine_id_fkey FOREIGN KEY (typesofmachine_id) REFERENCES public.types_of_machines(id) ON DELETE CASCADE;
 J   ALTER TABLE ONLY public.cars DROP CONSTRAINT cars_typesofmachine_id_fkey;
       public          postgres    false    231    3286    233            н           2606    35250 )   machines machines_machines_status_id_fkey 
   FK CONSTRAINT     Ї   ALTER TABLE ONLY public.machines
    ADD CONSTRAINT machines_machines_status_id_fkey FOREIGN KEY (machines_status_id) REFERENCES public.machines_status(id) ON DELETE CASCADE;
 S   ALTER TABLE ONLY public.machines DROP CONSTRAINT machines_machines_status_id_fkey;
       public          postgres    false    3274    222    218            о           2606    35245 "   machines machines_workshop_id_fkey 
   FK CONSTRAINT     ›   ALTER TABLE ONLY public.machines
    ADD CONSTRAINT machines_workshop_id_fkey FOREIGN KEY (workshop_id) REFERENCES public.workshops(id) ON DELETE CASCADE;
 L   ALTER TABLE ONLY public.machines DROP CONSTRAINT machines_workshop_id_fkey;
       public          postgres    false    3276    220    222            т           2606    35293 4   material_workshop material_workshop_material_id_fkey 
   FK CONSTRAINT     ­   ALTER TABLE ONLY public.material_workshop
    ADD CONSTRAINT material_workshop_material_id_fkey FOREIGN KEY (material_id) REFERENCES public.workshops(id) ON DELETE CASCADE;
 ^   ALTER TABLE ONLY public.material_workshop DROP CONSTRAINT material_workshop_material_id_fkey;
       public          postgres    false    220    3276    228            у           2606    35298 4   material_workshop material_workshop_workshop_id_fkey 
   FK CONSTRAINT     ­   ALTER TABLE ONLY public.material_workshop
    ADD CONSTRAINT material_workshop_workshop_id_fkey FOREIGN KEY (workshop_id) REFERENCES public.materials(id) ON DELETE CASCADE;
 ^   ALTER TABLE ONLY public.material_workshop DROP CONSTRAINT material_workshop_workshop_id_fkey;
       public          postgres    false    227    3284    228            п           2606    35270    staff staff_machine_id_fkey 
   FK CONSTRAINT     ’   ALTER TABLE ONLY public.staff
    ADD CONSTRAINT staff_machine_id_fkey FOREIGN KEY (machine_id) REFERENCES public.machines(id) ON DELETE CASCADE;
 E   ALTER TABLE ONLY public.staff DROP CONSTRAINT staff_machine_id_fkey;
       public          postgres    false    3278    222    224            р           2606    35265    staff staff_shift_id_fkey 
   FK CONSTRAINT     ‹   ALTER TABLE ONLY public.staff
    ADD CONSTRAINT staff_shift_id_fkey FOREIGN KEY (shift_id) REFERENCES public.shift(id) ON DELETE CASCADE;
 C   ALTER TABLE ONLY public.staff DROP CONSTRAINT staff_shift_id_fkey;
       public          postgres    false    224    216    3272            с           2606    35275    staff staff_workshop_id_fkey 
   FK CONSTRAINT     •   ALTER TABLE ONLY public.staff
    ADD CONSTRAINT staff_workshop_id_fkey FOREIGN KEY (workshop_id) REFERENCES public.workshops(id) ON DELETE CASCADE;
 F   ALTER TABLE ONLY public.staff DROP CONSTRAINT staff_workshop_id_fkey;
       public          postgres    false    220    3276    224            ф           2606    35313 4   types_of_machines types_of_machines_workshop_id_fkey 
   FK CONSTRAINT     ­   ALTER TABLE ONLY public.types_of_machines
    ADD CONSTRAINT types_of_machines_workshop_id_fkey FOREIGN KEY (workshop_id) REFERENCES public.workshops(id) ON DELETE CASCADE;
 ^   ALTER TABLE ONLY public.types_of_machines DROP CONSTRAINT types_of_machines_workshop_id_fkey;
       public          postgres    false    231    3276    220            Є
     xњmQKJЕ@\чњ"'ђLюЮЕГ$ПЌ`@ьЂ ‚ПЌёЊљСшbвjndM:Џ‡вўaRU]]Э±‚;_ыsЊҐЊгX¬IVМџЎ›(
.СбЌхЋ	vR)“QNфіЯH®X.ёБ+mZЙ+[8|±&ЯFёжзЅШ@&¦<МЬЎ‹–о!LукG!©
+Б™‘5Ўчµє'жXрА5
яЅЮЖ‚gi‚‘ЇCt)•kCO ъe§ПW\eФf*xЉ[Шjey“GвЅN„Ун3cy’­?eмV’КчЫУ)ВџyґО7„ж%Я Ч є7ќ№Ґ¤ЖЙЌ-vpQшIlnШ\®ЄкъЕЙ‘1ж,·ъ      Ё
   \   xњ3дООOITрO.I,ЛLд4б4202Ц5°Ф52T04¶20 "mc.#N'Яp…\SNЁ
s°
#„
cО0џ0…bё"]#C„ў=... ъ‹э      ±
   4   xњ
ЖБ	 0±w=L!v’iєяЅ‡@uJFPЗЬЬ<<<јyужГ‡_ѕ|х®¤bН	"      °
   r   xњ3дј0лbУ…}
/l№°хВо.мVёШqaЧ…}¶\lж4202Ц50Ц52R00°#mcО?NCд2Вj„“o8TЇЅF@ќFњF\ЖXх†щы„щCu[bСmФmМiМЈЗЕЕ D™E/      ¦
   `   xњ
К©
Ђ@…aЅSђpuC1‰AбpИеШ@ @яtДёw|‰cФ–ѓ—/©c°pІбµ!pk/™^­М,\ш€Џ`5°›к$wLxnы)і­µЦњRЖ"т";;“      ®
   ф   xњ…ђ]JГP…џп]EVљ¤iУЅё¤­дЎ…ZP© ">Я6¦$7?nбМЋ<7BDтrоњ3уН
OиСЙZRXYу‡ЪCGYЈUш .(:X:/
”Ѕ¤
'Tr;ШWЎКUІZДIґZЖa Pш8J*цМ`=Щ ссЋjhоЮ\Єчрй‡±В3Њд,4І§Ў‚Хб4Э‘MО7(Ыs-й¶”µВ+%sїеH8›%б|ю?блРДЊlф=R¶Ю_DMCє•›џгЭгкР`]К0схлtQ0y»~ШfјЌ/њrжК9‡ФъЖЧZЎН%a      µ
       xњ3д4д2д4bc.#N 6е2тcфёёё 4Ћv      ¶
      xњ3д4д2bc ЋСгвв (      ґ
   B   xњ3д4д4202Ц5°Ф52T04¶20 "mcda#„°!—§І¤ЃV=(Fqsв–ДnЏ1WЊ ы®'      ¬
   B   xњ3дј°рВЖы.6 qы…Ѕ»/мTёШvaлЕVОЛЂјН6\Ш{aЧ…}6)\ЄwaЋWЊ )m!є      І
      xњ3д4д2д4bc 6bS®=... 'sь      ¤
   
   xњ‹Сгвв Е ©      ™
   
   xњ‹Сгвв Е ©      •
   
   xњ‹Сгвв Е ©      џ
   
   xњ‹Сгвв Е ©      ћ
   
   xњ‹Сгвв Е ©      “
   
   xњ‹Сгвв Е ©      ›
   
   xњ‹Сгвв Е ©      ў
   
   xњ‹Сгвв Е ©      —
   
   xњ‹Сгвв Е ©     