create schema production;

create table production.region
(
	id integer primary key generated by default as identity,
	title text not null
);


create table production.product
(
	id integer primary key generated by default as identity,
	title text not null,
	complexity int not null,
	DateCreated timestamp(6) with time zone not null
);

create table production.knot
(
	id integer primary key generated by default as identity,
	title text not null,
	cost int not null,
	region_id int not null,
	foreign key(region_id) references production.region(id)
	on delete cascade
);

create table production.workshop
(
	id integer primary key generated by default as identity,
	title text not null,
	chef_name text not null
);

create table production.staff
(
	id integer primary key generated by default as identity,
	title text not null,
	first_name text not null,
	second_name text not null,
	last_name text not null,
	phone_number text not null unique,
	adres text not null unique,
	post text not null unique
);

create table production.production
(
	id integer primary key generated by default as identity,
	title text not null,
	DateCreated timestamp(6) with time zone not null,
	DateDelete timestamp(6) with time zone,
	product_id int not null,
	workshop_id int not null,
	region_id int not null,
	staff_id int not null,
	foreign key(product_id) references production.product(id)
	on delete cascade,
	foreign key(workshop_id) references production.workshop(id)
	on delete cascade,
	foreign key(region_id) references production.region(id)
	on delete cascade,
	foreign key(staff_id) references production.staff(id)
	on delete cascade
);


create table production.product_knot
(
	product_id int not null,
	knot_id int not null,
	foreign key(product_id) references production.product(id)
	on delete cascade,
	foreign key(knot_id) references production.knot(id)
	on delete cascade
);

create table production.workshop_region
(
	workshop_id int not null,
	region_id int not null,
	foreign key(workshop_id) references production.workshop(id)
	on delete cascade,
	foreign key(region_id) references production.region(id)
	on delete cascade
);


create table production.working_shift
(
	id integer primary key generated by default as identity,
	title text not null,
	shift_start_date timestamp(6) with time zone not null,
	shift_end_date timestamp(6) with time zone not null,
	staff_id int not null,
	foreign key(staff_id) references production.staff(id)
	on delete cascade
);


create table production.staff_region
(
	staff_id int not null,
	region_id int not null,
	foreign key(staff_id) references production.staff(id)
	on delete cascade,
	foreign key(region_id) references production.region(id)
	on delete cascade
);

create table production.staff_workshop
(
	staff_id int not null,
	workshop_id int not null,
	foreign key(staff_id) references production.staff(id)
	on delete cascade,
	foreign key(workshop_id) references production.workshop(id)
	on delete cascade
);